package com.mcslocation;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mcslocation.greendao.mapdetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig mapdetailsDaoConfig;

    private final mapdetailsDao mapdetailsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        mapdetailsDaoConfig = daoConfigMap.get(mapdetailsDao.class).clone();
        mapdetailsDaoConfig.initIdentityScope(type);

        mapdetailsDao = new mapdetailsDao(mapdetailsDaoConfig, this);

        registerDao(mapdetails.class, mapdetailsDao);
    }
    
    public void clear() {
        mapdetailsDaoConfig.clearIdentityScope();
    }

    public mapdetailsDao getMapdetailsDao() {
        return mapdetailsDao;
    }

}
