package com.mcslocation;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.mcslocation.greendao.mapdetails;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MAPDETAILS".
*/
public class mapdetailsDao extends AbstractDao<mapdetails, Long> {

    public static final String TABLENAME = "MAPDETAILS";

    /**
     * Properties of entity mapdetails.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Success = new Property(1, String.class, "Success", false, "SUCCESS");
        public final static Property PhoneName = new Property(2, String.class, "PhoneName", false, "PHONE_NAME");
        public final static Property PhoneNumber = new Property(3, String.class, "PhoneNumber", false, "PHONE_NUMBER");
        public final static Property DataTime = new Property(4, String.class, "DataTime", false, "DATA_TIME");
        public final static Property ClientTime = new Property(5, String.class, "ClientTime", false, "CLIENT_TIME");
        public final static Property ServerTime = new Property(6, String.class, "ServerTime", false, "SERVER_TIME");
        public final static Property LocType = new Property(7, int.class, "LocType", false, "LOC_TYPE");
        public final static Property Latitude = new Property(8, double.class, "Latitude", false, "LATITUDE");
        public final static Property Longitude = new Property(9, double.class, "Longitude", false, "LONGITUDE");
        public final static Property Radius = new Property(10, float.class, "Radius", false, "RADIUS");
        public final static Property City = new Property(11, String.class, "City", false, "CITY");
        public final static Property District = new Property(12, String.class, "District", false, "DISTRICT");
        public final static Property Street = new Property(13, String.class, "Street", false, "STREET");
        public final static Property AddrStr = new Property(14, String.class, "AddrStr", false, "ADDR_STR");
        public final static Property UserIndoorState = new Property(15, int.class, "UserIndoorState", false, "USER_INDOOR_STATE");
        public final static Property LocationDescribe = new Property(16, String.class, "LocationDescribe", false, "LOCATION_DESCRIBE");
        public final static Property PoiList = new Property(17, String.class, "PoiList", false, "POI_LIST");
        public final static Property Operators = new Property(18, int.class, "Operators", false, "OPERATORS");
        public final static Property Describe = new Property(19, String.class, "describe", false, "DESCRIBE");
        public final static Property IsNetAble = new Property(20, String.class, "isNetAble", false, "IS_NET_ABLE");
        public final static Property IsWifiAble = new Property(21, String.class, "isWifiAble", false, "IS_WIFI_ABLE");
        public final static Property GPSStatus = new Property(22, String.class, "GPSStatus", false, "GPSSTATUS");
        public final static Property IndoorLocationSurpport = new Property(23, int.class, "IndoorLocationSurpport", false, "INDOOR_LOCATION_SURPPORT");
        public final static Property IndoorLocationSource = new Property(24, int.class, "IndoorLocationSource", false, "INDOOR_LOCATION_SOURCE");
        public final static Property IndoorNetworkState = new Property(25, int.class, "IndoorNetworkState", false, "INDOOR_NETWORK_STATE");
        public final static Property IndoorLocationSurpportBuidlingName = new Property(26, String.class, "IndoorLocationSurpportBuidlingName", false, "INDOOR_LOCATION_SURPPORT_BUIDLING_NAME");
        public final static Property IndoorLocMode = new Property(27, String.class, "IndoorLocMode", false, "INDOOR_LOC_MODE");
        public final static Property BuildingName = new Property(28, String.class, "BuildingName", false, "BUILDING_NAME");
        public final static Property Floor = new Property(29, String.class, "Floor", false, "FLOOR");
        public final static Property GpsAccuracyStatus = new Property(30, int.class, "GpsAccuracyStatus", false, "GPS_ACCURACY_STATUS");
        public final static Property Networktype = new Property(31, String.class, "networktype", false, "NETWORKTYPE");
    }


    public mapdetailsDao(DaoConfig config) {
        super(config);
    }
    
    public mapdetailsDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MAPDETAILS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"SUCCESS\" TEXT," + // 1: Success
                "\"PHONE_NAME\" TEXT," + // 2: PhoneName
                "\"PHONE_NUMBER\" TEXT," + // 3: PhoneNumber
                "\"DATA_TIME\" TEXT," + // 4: DataTime
                "\"CLIENT_TIME\" TEXT," + // 5: ClientTime
                "\"SERVER_TIME\" TEXT," + // 6: ServerTime
                "\"LOC_TYPE\" INTEGER NOT NULL ," + // 7: LocType
                "\"LATITUDE\" REAL NOT NULL ," + // 8: Latitude
                "\"LONGITUDE\" REAL NOT NULL ," + // 9: Longitude
                "\"RADIUS\" REAL NOT NULL ," + // 10: Radius
                "\"CITY\" TEXT," + // 11: City
                "\"DISTRICT\" TEXT," + // 12: District
                "\"STREET\" TEXT," + // 13: Street
                "\"ADDR_STR\" TEXT," + // 14: AddrStr
                "\"USER_INDOOR_STATE\" INTEGER NOT NULL ," + // 15: UserIndoorState
                "\"LOCATION_DESCRIBE\" TEXT," + // 16: LocationDescribe
                "\"POI_LIST\" TEXT," + // 17: PoiList
                "\"OPERATORS\" INTEGER NOT NULL ," + // 18: Operators
                "\"DESCRIBE\" TEXT," + // 19: describe
                "\"IS_NET_ABLE\" TEXT," + // 20: isNetAble
                "\"IS_WIFI_ABLE\" TEXT," + // 21: isWifiAble
                "\"GPSSTATUS\" TEXT," + // 22: GPSStatus
                "\"INDOOR_LOCATION_SURPPORT\" INTEGER NOT NULL ," + // 23: IndoorLocationSurpport
                "\"INDOOR_LOCATION_SOURCE\" INTEGER NOT NULL ," + // 24: IndoorLocationSource
                "\"INDOOR_NETWORK_STATE\" INTEGER NOT NULL ," + // 25: IndoorNetworkState
                "\"INDOOR_LOCATION_SURPPORT_BUIDLING_NAME\" TEXT," + // 26: IndoorLocationSurpportBuidlingName
                "\"INDOOR_LOC_MODE\" TEXT," + // 27: IndoorLocMode
                "\"BUILDING_NAME\" TEXT," + // 28: BuildingName
                "\"FLOOR\" TEXT," + // 29: Floor
                "\"GPS_ACCURACY_STATUS\" INTEGER NOT NULL ," + // 30: GpsAccuracyStatus
                "\"NETWORKTYPE\" TEXT);"); // 31: networktype
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MAPDETAILS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, mapdetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Success = entity.getSuccess();
        if (Success != null) {
            stmt.bindString(2, Success);
        }
 
        String PhoneName = entity.getPhoneName();
        if (PhoneName != null) {
            stmt.bindString(3, PhoneName);
        }
 
        String PhoneNumber = entity.getPhoneNumber();
        if (PhoneNumber != null) {
            stmt.bindString(4, PhoneNumber);
        }
 
        String DataTime = entity.getDataTime();
        if (DataTime != null) {
            stmt.bindString(5, DataTime);
        }
 
        String ClientTime = entity.getClientTime();
        if (ClientTime != null) {
            stmt.bindString(6, ClientTime);
        }
 
        String ServerTime = entity.getServerTime();
        if (ServerTime != null) {
            stmt.bindString(7, ServerTime);
        }
        stmt.bindLong(8, entity.getLocType());
        stmt.bindDouble(9, entity.getLatitude());
        stmt.bindDouble(10, entity.getLongitude());
        stmt.bindDouble(11, entity.getRadius());
 
        String City = entity.getCity();
        if (City != null) {
            stmt.bindString(12, City);
        }
 
        String District = entity.getDistrict();
        if (District != null) {
            stmt.bindString(13, District);
        }
 
        String Street = entity.getStreet();
        if (Street != null) {
            stmt.bindString(14, Street);
        }
 
        String AddrStr = entity.getAddrStr();
        if (AddrStr != null) {
            stmt.bindString(15, AddrStr);
        }
        stmt.bindLong(16, entity.getUserIndoorState());
 
        String LocationDescribe = entity.getLocationDescribe();
        if (LocationDescribe != null) {
            stmt.bindString(17, LocationDescribe);
        }
 
        String PoiList = entity.getPoiList();
        if (PoiList != null) {
            stmt.bindString(18, PoiList);
        }
        stmt.bindLong(19, entity.getOperators());
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(20, describe);
        }
 
        String isNetAble = entity.getIsNetAble();
        if (isNetAble != null) {
            stmt.bindString(21, isNetAble);
        }
 
        String isWifiAble = entity.getIsWifiAble();
        if (isWifiAble != null) {
            stmt.bindString(22, isWifiAble);
        }
 
        String GPSStatus = entity.getGPSStatus();
        if (GPSStatus != null) {
            stmt.bindString(23, GPSStatus);
        }
        stmt.bindLong(24, entity.getIndoorLocationSurpport());
        stmt.bindLong(25, entity.getIndoorLocationSource());
        stmt.bindLong(26, entity.getIndoorNetworkState());
 
        String IndoorLocationSurpportBuidlingName = entity.getIndoorLocationSurpportBuidlingName();
        if (IndoorLocationSurpportBuidlingName != null) {
            stmt.bindString(27, IndoorLocationSurpportBuidlingName);
        }
 
        String IndoorLocMode = entity.getIndoorLocMode();
        if (IndoorLocMode != null) {
            stmt.bindString(28, IndoorLocMode);
        }
 
        String BuildingName = entity.getBuildingName();
        if (BuildingName != null) {
            stmt.bindString(29, BuildingName);
        }
 
        String Floor = entity.getFloor();
        if (Floor != null) {
            stmt.bindString(30, Floor);
        }
        stmt.bindLong(31, entity.getGpsAccuracyStatus());
 
        String networktype = entity.getNetworktype();
        if (networktype != null) {
            stmt.bindString(32, networktype);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, mapdetails entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String Success = entity.getSuccess();
        if (Success != null) {
            stmt.bindString(2, Success);
        }
 
        String PhoneName = entity.getPhoneName();
        if (PhoneName != null) {
            stmt.bindString(3, PhoneName);
        }
 
        String PhoneNumber = entity.getPhoneNumber();
        if (PhoneNumber != null) {
            stmt.bindString(4, PhoneNumber);
        }
 
        String DataTime = entity.getDataTime();
        if (DataTime != null) {
            stmt.bindString(5, DataTime);
        }
 
        String ClientTime = entity.getClientTime();
        if (ClientTime != null) {
            stmt.bindString(6, ClientTime);
        }
 
        String ServerTime = entity.getServerTime();
        if (ServerTime != null) {
            stmt.bindString(7, ServerTime);
        }
        stmt.bindLong(8, entity.getLocType());
        stmt.bindDouble(9, entity.getLatitude());
        stmt.bindDouble(10, entity.getLongitude());
        stmt.bindDouble(11, entity.getRadius());
 
        String City = entity.getCity();
        if (City != null) {
            stmt.bindString(12, City);
        }
 
        String District = entity.getDistrict();
        if (District != null) {
            stmt.bindString(13, District);
        }
 
        String Street = entity.getStreet();
        if (Street != null) {
            stmt.bindString(14, Street);
        }
 
        String AddrStr = entity.getAddrStr();
        if (AddrStr != null) {
            stmt.bindString(15, AddrStr);
        }
        stmt.bindLong(16, entity.getUserIndoorState());
 
        String LocationDescribe = entity.getLocationDescribe();
        if (LocationDescribe != null) {
            stmt.bindString(17, LocationDescribe);
        }
 
        String PoiList = entity.getPoiList();
        if (PoiList != null) {
            stmt.bindString(18, PoiList);
        }
        stmt.bindLong(19, entity.getOperators());
 
        String describe = entity.getDescribe();
        if (describe != null) {
            stmt.bindString(20, describe);
        }
 
        String isNetAble = entity.getIsNetAble();
        if (isNetAble != null) {
            stmt.bindString(21, isNetAble);
        }
 
        String isWifiAble = entity.getIsWifiAble();
        if (isWifiAble != null) {
            stmt.bindString(22, isWifiAble);
        }
 
        String GPSStatus = entity.getGPSStatus();
        if (GPSStatus != null) {
            stmt.bindString(23, GPSStatus);
        }
        stmt.bindLong(24, entity.getIndoorLocationSurpport());
        stmt.bindLong(25, entity.getIndoorLocationSource());
        stmt.bindLong(26, entity.getIndoorNetworkState());
 
        String IndoorLocationSurpportBuidlingName = entity.getIndoorLocationSurpportBuidlingName();
        if (IndoorLocationSurpportBuidlingName != null) {
            stmt.bindString(27, IndoorLocationSurpportBuidlingName);
        }
 
        String IndoorLocMode = entity.getIndoorLocMode();
        if (IndoorLocMode != null) {
            stmt.bindString(28, IndoorLocMode);
        }
 
        String BuildingName = entity.getBuildingName();
        if (BuildingName != null) {
            stmt.bindString(29, BuildingName);
        }
 
        String Floor = entity.getFloor();
        if (Floor != null) {
            stmt.bindString(30, Floor);
        }
        stmt.bindLong(31, entity.getGpsAccuracyStatus());
 
        String networktype = entity.getNetworktype();
        if (networktype != null) {
            stmt.bindString(32, networktype);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public mapdetails readEntity(Cursor cursor, int offset) {
        mapdetails entity = new mapdetails( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Success
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // PhoneName
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // PhoneNumber
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // DataTime
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // ClientTime
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // ServerTime
            cursor.getInt(offset + 7), // LocType
            cursor.getDouble(offset + 8), // Latitude
            cursor.getDouble(offset + 9), // Longitude
            cursor.getFloat(offset + 10), // Radius
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // City
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // District
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Street
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // AddrStr
            cursor.getInt(offset + 15), // UserIndoorState
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // LocationDescribe
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // PoiList
            cursor.getInt(offset + 18), // Operators
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // describe
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // isNetAble
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // isWifiAble
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // GPSStatus
            cursor.getInt(offset + 23), // IndoorLocationSurpport
            cursor.getInt(offset + 24), // IndoorLocationSource
            cursor.getInt(offset + 25), // IndoorNetworkState
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // IndoorLocationSurpportBuidlingName
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // IndoorLocMode
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // BuildingName
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // Floor
            cursor.getInt(offset + 30), // GpsAccuracyStatus
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31) // networktype
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, mapdetails entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setSuccess(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setPhoneName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhoneNumber(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setDataTime(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setClientTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setServerTime(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setLocType(cursor.getInt(offset + 7));
        entity.setLatitude(cursor.getDouble(offset + 8));
        entity.setLongitude(cursor.getDouble(offset + 9));
        entity.setRadius(cursor.getFloat(offset + 10));
        entity.setCity(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setDistrict(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setStreet(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setAddrStr(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setUserIndoorState(cursor.getInt(offset + 15));
        entity.setLocationDescribe(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setPoiList(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setOperators(cursor.getInt(offset + 18));
        entity.setDescribe(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setIsNetAble(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setIsWifiAble(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setGPSStatus(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setIndoorLocationSurpport(cursor.getInt(offset + 23));
        entity.setIndoorLocationSource(cursor.getInt(offset + 24));
        entity.setIndoorNetworkState(cursor.getInt(offset + 25));
        entity.setIndoorLocationSurpportBuidlingName(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setIndoorLocMode(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setBuildingName(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setFloor(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setGpsAccuracyStatus(cursor.getInt(offset + 30));
        entity.setNetworktype(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(mapdetails entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(mapdetails entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(mapdetails entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
